### ISSUE TITLE
ng-bootstrap not working

### ISSUE THREAD

**Issue by Angelo510** [gdi2290/angular-starter#1890]
Hello,

I have just cloned the repo and add ng-bootstrap using ```npm install --save @ng-bootstrap/ng-bootstrap```.
But bootstrap is not working while I put just simple classes like ```container``` and ```col-sm-4```.
I have configured which is guided on https://github.com/ng-bootstrap/ng-bootstrap but it seems bootstrap is not working.
Can you please let me know how to handle this issue?

Thanks.

**Comment by colinskow** [comment]
Follow these instructions:
https://github.com/AngularClass/angular-starter#external-stylesheets

**Comment by bogdy29** [comment]
I followed that instructions and not working also for me

**Comment by lanovoy** [comment]
I've updated readme with a correct import statement. Use ~ prefix to import from the node_modules subfolder.
