### ISSUE TITLE
Make use of @angular/cli build optimizer

### ISSUE THREAD

**Issue by craigsnyders** [gdi2290/angular-starter#1894]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Although the project uses AOT, I don't believe it's making use of the new `--build-optimizer` option

* **What is the motivation / use case for changing the behavior?**
Reduce overall module size for AOT and prod builds

* **Other information** 
https://github.com/angular/angular-cli/pull/6520
I noticed that `--build-optimizer` exists while debugging my own project's large build sizes. I found that `material.es5.js` was not minified / tree shaken as much as I hoped, which led me to https://github.com/angular/material2/issues/4137 and then the above PR.

**Comment by lanovoy** [comment]
It's using the build optimizer. See  config/build-utils.js
