### ISSUE TITLE
Set checkbox state from string value

### ISSUE THREAD

**Issue by A-Roller** [gdi2290/angular-starter#1897]
This might be a very stupid question but I just can't figure out the right way to do it. 
I want to set the initial state of a checkbox based the value of the variable. 
The value of the variable is "true" and "false" but its a string, not a boolean so the checkbox as checked on the load even if the variable value is false.

example - 
In .html i have  <input type="checkbox" name="isActive" [(ngModel)]="user.isActive">
and in .ts 
ngOnInit() {
    this.user = {
      isActive: "false"
    }

What is the best way to handle this scenario on HTML side?

**Comment by lmarcelocc** [comment]
Hi,

I'm not an expert but, can't you do something like this?
```
checkBooleanFromString(val) : boolean {
    if (val.toLowerCase(val) === 'true') {
        return true;
    }

    return false;
}

ngOnInit() {

    this.user = {
        isActive: this.checkBooleanFromString("false")
    }
}
```

**Comment by lanovoy** [comment]
Use stackoverflow for questions like this.
