### ISSUE TITLE
IE 11 not supported

### ISSUE THREAD

**Issue by geoHeil** [gdi2290/angular-starter#1907]
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
On Internet explorer 11 javascript is not working properly. When checking out the starter the minimal sample app (here on GitHub) is stuck on Loading ... indicator

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

```
git clone --depth 1 https://github.com/AngularClass/angular-starter.git

# change directory to our repo
cd angular-starter
yarn install
yarn server:dev:hmr
```

* **What is the expected behavior?**
to actually see the angular app instead of a white web page. Chrome & Firefox work just fine

- Angular version: just like current minimal sample app
- Browser: IE11 has problems, Chrome + Firefox work just fine

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
no error message shown in internet explorer console

**Comment by Georg-Beischlager** [comment]
I also encountered this problem, i have additional information:

An exception is thrown in the _for-of.js File on IE Startup.

```
var ctx = require('./_ctx');
var call = require('./_iter-call');
var isArrayIter = require('./_is-array-iter');
var anObject = require('./_an-object');
var toLength = require('./_to-length');
var getIterFn = require('./core.get-iterator-method');
var BREAK = {};
var RETURN = {};
var exports = module.exports = function (iterable, entries, fn, that, ITERATOR) {
  var iterFn = ITERATOR ? function () { return iterable; } : getIterFn(iterable);
  var f = ctx(fn, that, entries ? 2 : 1);
  var index = 0;
  var length, step, iterator, result;
  if (typeof iterFn != 'function') throw TypeError(iterable + ' is not iterable!'); // ERROR IS THROWN HERE
  // fast case for arrays with default iterator
  if (isArrayIter(iterFn)) for (length = toLength(iterable.length); length > index; index++) {
    result = entries ? f(anObject(step = iterable[index])[0], step[1]) : f(iterable[index]);
    if (result === BREAK || result === RETURN) return result;
  } else for (iterator = iterFn.call(iterable); !(step = iterator.next()).done;) {
    result = call(iterator, f, step.value, entries);
    if (result === BREAK || result === RETURN) return result;
  }
};
exports.BREAK = BREAK;
exports.RETURN = RETURN;



//////////////////
// WEBPACK FOOTER
// ./node_modules/core-js/modules/_for-of.js
// module id = ./node_modules/core-js/modules/_for-of.js
// module chunks = 1
```

**Comment by Georg-Beischlager** [comment]
Okay, so it turns out I should read the polyfills file before commenting here.

There is a block in src/polyfills.browser.ts where polyfills for IE9,10 & 11 need to be activated. Works perfectly afterwards.

I think that should solve all problems.

**Comment by Georg-Beischlager** [comment]
Okay, so it turns out I should read the polyfills file before commenting here.

There is a block in src/polyfills.browser.ts where polyfills for IE9,10 & 11 need to be activated. Works perfectly afterwards.

I think that should solve all problems.

**Comment by geoHeil** [comment]
you mean https://github.com/gdi2290/angular-starter/blob/6dd6d0d6567481f74d01ccf813bb066e13abfa97/src/polyfills.browser.ts#L24 thanks!
