### ISSUE TITLE
declare module '*' creates problems in VSCode

### ISSUE THREAD

**Issue by JonWallsten** [gdi2290/angular-starter#1918]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
VSCode does not report problems with for example broken import paths or missing exports.
Following any module with cmd+click ends up in the custom-typings.ts.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
This is an IDE specific issue and cannot be shown in a playground.
But the issue is in the custom-typings.ts file.

* **What is the expected behavior?**
VSCode should report issues with broken import paths or missing exports
Following a module with cmd+click should take you to that module or it's definition file

* **What is the motivation / use case for changing the behavior?**
The IDE would work like expected if this is handled.

* **Please tell us about your environment:**

- Typescript version: 2.5.3
- VSCode version: 1.18.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
The issue is this line in custom-typings.ts
```
declare module '*';
```
I would guess it's because VSCode interprets this as the source of all imported modules.
I can of course just remove this line in my project. But I guess this might affect other users as well. So I just wanted to point out that the problem exists.

**Comment by lanovoy** [comment]
Questions like this better be addressed to the stackoverflow...
