### ISSUE TITLE
Lazy Loaded Component is not generating a #.chunk.js

### ISSUE THREAD

**Issue by ZacharyLangley** [gdi2290/angular-starter#1919]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[*] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

I'm trying to add a new component, but I'm running into a problem. I created a new test component to figure out how to add a new component. I lazy loaded it into the app.routes.ts, but a #.chunk.js is not generated. The routes work to get to the to test component from the navbar.

**index.ts**
`export { TestModule } from './test.module';`

**test.component.ts**

```
import {
    Component,
    OnInit,
} from '@angular/core';

@Component({
    selector: 'app-test',
    templateUrl: './test.component.html',
    styleUrls: [ './test.component.css', ],
})

export class TestComponent implements OnInit {
    public ngOnInit () {
        console.log('Hello from the Test Component');
    }
}
```

**test.module.ts** 
```
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';

import { routes } from './test.routes';
import { TestComponent } from './test.component';

@NgModule ({
    declarations: [
        TestComponent,
    ],
    imports: [
        CommonModule,
        FormsModule,
        RouterModule.forChild(routes),
    ]
})

export class TestModule {
    public static routes = routes;
}
```

**test.routes.ts**
```
import { TestComponent } from './test.component';

export const routes = [
    { path: '', children: [
        { path: '', component: TestComponent },
    ]},
];
```

**app.routes.ts** 
```
import { Routes } from '@angular/router';
import { HomeComponent } from './home';
import { AboutComponent } from './about';
import { NoContentComponent } from './no-content';

import { DataResolver } from './app.resolver';

export const ROUTES: Routes = [
  { path: '',      component: HomeComponent },
  { path: 'home',  component: HomeComponent },
  { path: 'about', component: AboutComponent },
  { path: 'detail', loadChildren: './+detail#DetailModule'},
  { path: 'barrel', loadChildren: './+barrel#BarrelModule'},
  { path: 'test', loadChildren: './+test#TestModule'},
  { path: '**',    component: NoContentComponent },
];
```

app.component.ts
```
/**
 * Angular 2 decorators and services
 */
import {
  Component,
  OnInit,
  ViewEncapsulation
} from '@angular/core';
import { AppState } from './app.service';

/**
 * App Component
 * Top Level Component
 */
@Component({
  selector: 'app',
  encapsulation: ViewEncapsulation.None,
  styleUrls: [
    './app.component.css'
  ],
  template: `
    <nav>
      <a [routerLink]=" ['./'] "
        routerLinkActive="active" [routerLinkActiveOptions]= "{exact: true}">
        Index
      </a>
      <a [routerLink]=" ['./home'] "
        routerLinkActive="active" [routerLinkActiveOptions]= "{exact: true}">
        Home
      </a>
      <a [routerLink]=" ['./detail'] "
        routerLinkActive="active" [routerLinkActiveOptions]= "{exact: true}">
        Detail
      </a>
      <a [routerLink]=" ['./barrel'] "
        routerLinkActive="active" [routerLinkActiveOptions]= "{exact: true}">
        Barrel
      </a>
      <a [routerLink]=" ['./about'] "
        routerLinkActive="active" [routerLinkActiveOptions]= "{exact: true}">
        About
      </a>
      <a [routerLink]=" ['./test'] "
        routerLinkActive="active" [routerLinkActiveOptions]= "{exact: true}">
        Test
      </a>
    </nav>

    <main>
      <router-outlet></router-outlet>
    </main>

    <pre class="app-state">this.appState.state = {{ appState.state | json }}</pre>

    <footer>
      <span>WebPack Angular 2 Starter by <a [href]="url">@AngularClass</a></span>
      <div>
        <a [href]="url">
          <img [src]="angularclassLogo" width="25%">
        </a>
      </div>
    </footer>
  `
})
export class AppComponent implements OnInit {
  public angularclassLogo = 'assets/img/angularclass-avatar.png';
  public name = 'Angular 2 Webpack Starter';
  public url = 'https://twitter.com/AngularClass';

  constructor(
    public appState: AppState
  ) {}

  public ngOnInit() {
    console.log('Initial App State', this.appState.state);
  }

}
```

Could you provide some instruction on how to add a component to angular-starter and how to lazy load that component to generate a chunk.js

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

New Component generates a #.chunk.js

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by ZacharyLangley** [comment]
It works if i copy the details and barrel components into my test component. ,but it does not work on my new components

**Comment by Bjeaurn** [comment]
Why was this closed by you without any answer or explanation?

**Comment by ZacharyLangley** [comment]
I solved it on my own.

**Comment by Bjeaurn** [comment]
Mind sharing your solution? I’m running into similar issues but haven’t been able to figure it out yet.

**Comment by ZacharyLangley** [comment]
Yea sure, Ill post the code.
index.ts
`export { TestModule } from './test.module';`

test.component.ts
`import {
    Component,
    OnInit,
} from '@angular/core';

@Component({
    selector: 'test',
    templateUrl: './test.component.html',
})

export class TestComponent implements OnInit {
    public ngOnInit () {
        console.log('Hello from the Test Component');
    }
}`

test.module.ts
`import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';

import { routes } from './test.routes';
import { TestComponent } from './test.component';

@NgModule ({
    declarations: [
        TestComponent,
    ],
    imports: [
        CommonModule,
        FormsModule,
        RouterModule.forChild(routes),
    ]
})

export class TestModule {
    public static routes = routes;
}
`
test.routes.ts
`import { TestComponent } from './test.component';

export const routes = [
    { path: '', component: TestComponent },
];
`

app.module.ts
`import { HomeComponent } from './home';
import { AboutComponent } from './about';
import { NoContentComponent } from './no-content';
import { XLargeDirective } from './home/x-large';

import '../styles/styles.scss';
import '../styles/headings.css';
import { NoPreloading } from '@angular/router/src/router_preloader';

// Application wide providers
const APP_PROVIDERS = [
  ...APP_RESOLVER_PROVIDERS,
  AppState
];

type StoreType = {
  state: InternalStateType,
  restoreInputValues: () => void,
  disposeOldHosts: () => void
};

/**
 * `AppModule` is the main entry point into Angular2's bootstraping process
 */
@NgModule({
  bootstrap: [ AppComponent ],
  declarations: [
    AppComponent,
    AboutComponent,
    HomeComponent,
    NoContentComponent,
    XLargeDirective,
  ],
  /**
   * Import Angular's modules.
   */
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(ROUTES, {
      useHash: Boolean(history.pushState) === false,
      preloadingStrategy: PreloadAllModules
    })
  ],
  /**
   * Expose our Services and Providers into Angular's dependency injection.
   */
  providers: [
    ENV_PROVIDERS,
    APP_PROVIDERS
  ]
})
export class AppModule {

  constructor(
    public appRef: ApplicationRef,
    public appState: AppState
  ) {}

  public hmrOnInit(store: StoreType) {
    if (!store || !store.state) {
      return;
    }
    console.log('HMR store', JSON.stringify(store, null, 2));
    /**
     * Set state
     */
    this.appState._state = store.state;
    /**
     * Set input values
     */
    if ('restoreInputValues' in store) {
      let restoreInputValues = store.restoreInputValues;
      setTimeout(restoreInputValues);
    }

    this.appRef.tick();
    delete store.state;
    delete store.restoreInputValues;
  }

  public hmrOnDestroy(store: StoreType) {
    const cmpLocation = this.appRef.components.map((cmp) => cmp.location.nativeElement);
    /**
     * Save state
     */
    const state = this.appState._state;
    store.state = state;
    /**
     * Recreate root elements
     */
    store.disposeOldHosts = createNewHosts(cmpLocation);
    /**
     * Save input values
     */
    store.restoreInputValues  = createInputTransfer();
    /**
     * Remove styles
     */
    removeNgStyles();
  }

  public hmrAfterDestroy(store: StoreType) {
    /**
     * Display new elements
     */
    store.disposeOldHosts();
    delete store.disposeOldHosts;
  }

}
`

app.routes.ts
`import { Routes } from '@angular/router';
import { HomeComponent } from './home';
import { AboutComponent } from './about';
import { NoContentComponent } from './no-content';

import { DataResolver } from './app.resolver';

export const ROUTES: Routes = [
  { path: '',      component: HomeComponent },
  { path: 'home',  component: HomeComponent },
  { path: 'about', component: AboutComponent },
  { path: 'different', loadChildren: './+different#DifferentModule'},
  { path: 'barrel', loadChildren: './+barrel#BarrelModule'},
  { path: 'test', loadChildren: './+test#TestModule'},
  { path: '**',    component: NoContentComponent },
];`

**Comment by Bjeaurn** [comment]
May I suggest you prefix each block of code with \`\`\` and close it off with another \`\`\`?

**Comment by ZacharyLangley** [comment]
I understand, I keep forgetting that it even though I press the "code" button in the top bar, I need to press it 3 times or insert my own 3 `

**Comment by Bjeaurn** [comment]
Yeah takes some getting used to ;-). 

Anyway, I think the difference I spotted in a different issue is that the `DllModule` is now removed from webpack, and we rely a bit more on the `ChunkModule` from Webpack to our code splitted.

Seems to work in that way, the code you provided is in no way different from what's expected.
