### ISSUE TITLE
Error in prod build

### ISSUE THREAD

**Issue by MADzO** [gdi2290/angular-starter#1921]
After changing the configs to latest (to support Angular 5) I am getting the following error on the app after production build.

> Uncaught Error: Unexpected value 't' imported by the module 't'. Please add a @NgModule annotation.
    at l (compiler.js:466)
    at compiler.js:15089
    at Array.forEach (<anonymous>)
    at t.getNgModuleMetadata (compiler.js:15072)
    at t._loadModules (compiler.js:33501)
    at t._compileModuleAndComponents (compiler.js:33462)
    at t.compileModuleAsync (compiler.js:33378)
    at t.compileModuleAsync (platform-browser-dynamic.js:230)
    at t.bootstrapModule (core.js:5446)
    at kr (main.browser.ts:18)

**Comment by airbnbbkk** [comment]
I'm getting the exact same issue :(

**Comment by JCornat** [comment]
I have the issue when I run `npm run build:aot`, and serve it with my system.

Here my stack trace : 

```
Error: Unexpected value 'e' imported by the module 'e'. Please add a @NgModule annotation.
    at c (compiler.js:466)
    at compiler.js:15089
    at Array.forEach (<anonymous>)
    at e.getNgModuleMetadata (compiler.js:15072)
    at e._loadModules (compiler.js:33501)
    at e._compileModuleAndComponents (compiler.js:33462)
    at e.compileModuleAsync (compiler.js:33378)
    at e.compileModuleAsync (platform-browser-dynamic.js:230)
    at e.WT6e.e.bootstrapModule (core.js:5446)
    at main.browser.ts:9
```

As I was thinking it could come from my own modules, so I copy-paste the default `app.module.ts`, and shrinked it to the bare minimum, working in dev mode with command `npm run server` :

**app.component.ts :**

```
import { Component, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app',
  encapsulation: ViewEncapsulation.None,
  template: 'APP COMPONENT'
})
export class AppComponent {
}
```

**app.module.ts**

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';

@NgModule({
  bootstrap: [ AppComponent ],
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
  ],
})
export class AppModule {}
```

The error seems to produce in file `main.browser.ts`, when `platformBrowserDynamic().bootstrapModule(AppModule);` is executed.

Seems to be linked to an older issue in angular repo : [#15763](https://github.com/angular/angular/issues/15763), but no clear solution to me !

**Comment by aldokocha** [comment]
Having the same issue in production build, dev build is working fine though...

**Comment by JCornat** [comment]
@milosd92 Thanks for the temporary workaround, it works.

**Comment by milosd92** [comment]
Before i switched to AOT:

When i run `npm run build:prod` i get the same error as everyone else got, but after unmangling compiled code (switching mangle to `false`) https://github.com/gdi2290/angular-starter/blob/7ae83a76603246ff7d9c52999539706ae60ff7df/config/webpack.prod.js#L40

i get this error: 

> Uncaught Error: Unexpected value 'BrowserModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

After a little digging through compiler.js i found that decorators for BrowserModule can't be resolved, and resolve returns empty list. That will trigger this error above.

Another thing i noticed, when @airbnbbkk mentioned AOT builds, is that the build-optimizer is always on (even when building JIT) https://github.com/gdi2290/angular-starter/blob/7ae83a76603246ff7d9c52999539706ae60ff7df/config/build-utils.js#L111

not sure if that can be an issue, because using build-optimizer removes `ctorParameters` definitions from types. And `ctorParameters` are needed to initialize decorators for particular component. https://stackoverflow.com/a/46741873/5885415. I am not sure about this, take it with a grain of salt

Maybe there is a connection between these 'issues'.

**Comment by AnandkumarSP** [comment]
I guess @milosd92 is correct on`ctorParameters` removal. Disabling `buildOptimizer` in [build-utils.js](https://github.com/gdi2290/angular-starter/blob/1fb04c5a185efd5b3ae27ca1552b253c3f088bbc/config/build-utils.js#L78) solved this problem for time being.

Below is the change I did in [build-utils.js](https://github.com/gdi2290/angular-starter/blob/1fb04c5a185efd5b3ae27ca1552b253c3f088bbc/config/build-utils.js#L78),

```javascript
--   const buildOptimizer = prod;
++   const buildOptimizer = false;
```

**Comment by shlomiassaf** [comment]
Just to be on the safe side, are you all using TS 2.4.2 ? cause 2.5 is supported from 5.1.x (in RC now) and 2.6+ is not supported.

**Comment by shlomiassaf** [comment]
Also, the reason I created the `buildOptimizer` variable is to allow disabling it from a single place instead of changing code.

I did that because I found multiple projects of mine did not compile with it.

It is probably due to 3rd party libraries that are incompatible or create strange edge cases causing the optimizer to mess up the code.

**Comment by milosd92** [comment]
I am using TS 2.5.2 as specified in package.json
https://github.com/gdi2290/angular-starter/blob/7ae83a76603246ff7d9c52999539706ae60ff7df/package.json#L160

I tried with TS 2.4.2 but to no avail at all.

Maybe there is incompatibility with some 3rd party libs, as @shlomiassaf mentioned.

**Comment by shoudaos** [comment]
Is there any solution?

**Comment by milosd92** [comment]
@shoudaos Workaround for now is to use AOT build for production builds, that is what is recomened in angular v5. More on that on https://hackernoon.com/what-to-expect-for-in-angular-v5-6e0fc9c4b13e.

You can use my "workaround"
https://github.com/mocosha/angular-starter/commit/c406dea28c2a5a1c02e55bcbc9694e0ab4b1375d

But the problem with this is that you will need to make sure your project builds with AOT.

**Comment by anhtata** [comment]
compiler.js.pre-build-optimizer.js:485 Uncaught Error: Unexpected value 'Me' imported by the module 't'. Please add a @NgModule annotation.
    at c (compiler.js.pre-build-optimizer.js:485)
    at compiler.js.pre-build-optimizer.js:15204
    at Array.forEach (<anonymous>)
    at t.getNgModuleMetadata (compiler.js.pre-build-optimizer.js:15187)
    at t._loadModules (compiler.js.pre-build-optimizer.js:34226)
    at t._compileModuleAndComponents (compiler.js.pre-build-optimizer.js:34187)
    at t.compileModuleAsync (compiler.js.pre-build-optimizer.js:34081)
    at t.compileModuleAsync (platform-browser-dynamic.js.pre-build-optimizer.js:230)
    at t.bootstrapModule (core.js.pre-build-optimizer.js:5568)
    at Do (main.browser.ts:18)

I got same issue and don't know "Me" ...

**Comment by milosd92** [comment]
@anhtata I think you are getting the same error as everyone else.
That 'Me' variable is obfuscated and it's probably the first Module in imports array.

What error are you getting in AOT build?

**Comment by anhtata** [comment]
@milosd92 With AOT build, I got exit 2 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'webpack',
1 verbose cli   '--',
1 verbose cli   '--config',
1 verbose cli   'config/webpack.prod.js',
1 verbose cli   '--progress',
1 verbose cli   '--profile',
1 verbose cli   '--bail' ]
2 info using npm@5.6.0
3 info using node@v6.11.2
4 verbose run-script [ 'prewebpack', 'webpack', 'postwebpack' ]
5 info lifecycle home@1.1.0~prewebpack: home@1.1.0
6 info lifecycle home@1.1.0~webpack: home@1.1.0
7 verbose lifecycle home@1.1.0~webpack: unsafe-perm in lifecycle true
8 verbose lifecycle home@1.1.0~webpack: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/taanh/Projects/home/KmsHomeWeb/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/taanh/Projects/home/KmsHomeWeb/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet
9 verbose lifecycle home@1.1.0~webpack: CWD: /Users/taanh/Projects/home/KmsHomeWeb
10 silly lifecycle home@1.1.0~webpack: Args: [ '-c',
10 silly lifecycle   'node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"' ]
11 silly lifecycle home@1.1.0~webpack: Returned: code: 2  signal: null
12 info lifecycle home@1.1.0~webpack: Failed to exec webpack script
13 verbose stack Error: home@1.1.0 webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid home@1.1.0
15 verbose cwd /Users/taanh/Projects/home/KmsHomeWeb
16 verbose Darwin 17.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "webpack" "--" "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
18 verbose node v6.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error home@1.1.0 webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"`
22 error Exit status 2
23 error Failed at the home@1.1.0 webpack script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by tuoitrexuquang** [comment]
Hi, What's solution for this case?

**Comment by KeitaElric** [comment]
> You can use my "workaround"
> mocosha/angular-starter@c406dea
> 
> Just make sure your project follows the rules for building with AOT.

Its worked for me. Tks @milosd92

**Comment by Mc128k** [comment]
I had the same problem and I can confirm that the patch [here](https://github.com/lanovoy/angular-starter/commit/5708978df40c0ff17061ca39dd06727fa28b556b) worked

**Comment by chrisbellman** [comment]
Can confirm building with AOT fixed this problem. I'd still like to have JIT builds working, though.
The patch [here](https://github.com/lanovoy/angular-starter/commit/5708978df40c0ff17061ca39dd06727fa28b556b) did not work for me unfortunately :(.

**Comment by michal-kroliczek** [comment]
It's so pity so major bug is not fixed for so long time in master branch 👎
