### ISSUE TITLE
Chunks are not getting generated with @ngtools/webpack while upgrading to angular 5

### ISSUE THREAD

**Issue by krischandra** [gdi2290/angular-starter#1926]
Angular CLI: 1.5.0
Node: 6.10.1
Angular 5
@ngtools/webpack version: 1.8.2
Webpack.common.js
module: {
rules: [{
loader: '',
options: {
configFileName: 'tsconfig.webpack.json',
}
}],
plugins: [{
new AngularCompilerPlugin({
"sourceMap": true,
"tsConfigPath": helpers.root('tsconfig.webpack.json'),
"skipCodeGeneration": true,
"compilerOptions": {}
}),
}]
}

tsconfig.webpack.json

{
"compilerOptions": {
"outDir": "./compiled",
"sourceMap": true,
"declaration": false,
"moduleResolution": "node",
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"target": "es5",
"baseUrl": ".",
"paths": {
"@root/:[
"src/root/"
],
"@main/": [
"src/main/"
],
"@test/": [
"src/test/"
],
"@styles/": [
"src/style-sheets/"
]
},
"typeRoots": [
"node_modules/@types"
],
"lib": [
"es2015",
"dom"
]
},
"exclude": [
"node_modules",
],
"angularCompilerOptions": {
"genDir": "./compiled",
"skipMetadataEmit": true
},
"compileOnSave": false,
"buildOnSave": false,
"atom": {
"rewriteTsconfig": false
}
}

Actual result: Chunks is not getting generated for lazy loaded modules
Expected Result: Should generate chunks

**Comment by krischandra** [comment]
Issue with plugins.

**Comment by Bjeaurn** [comment]
Can you specify which plugin caused the error(s)? Or what is the final result of your `webpack.common.config`?

I'm running into lazy loading issues and can't seem to figure out where it's breaking.

**Comment by krischandra** [comment]
I removed DLL plugins from webpack.prod.js and its working fine

**Comment by Bjeaurn** [comment]
Are you separating your `vendor` and/or `polyfills` in a different way then?
