### ISSUE TITLE
Tag for Angular 4?

### ISSUE THREAD

**Issue by simonmcl** [gdi2290/angular-starter#1929]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **What is the current behavior?**

There doesn't seem to have been a release / tag on this repo since 27 Dec 2016, there are none that include Angular 4, but the current code is on Angular 5. Was there ever a stable release of a starter with Angular 4?

**Comment by simonmcl** [comment]
@gdi2290 was looking for a stable version with Angular 5, but tags still seem to be hugely out of date. ANy plan to address this?

**Comment by lanovoy** [comment]
Looks like tags were updated. Closing...
