### ISSUE TITLE
Error thrown: EmptyError: no elements in sequence

### ISSUE THREAD

**Issue by envil** [gdi2290/angular-starter#1932]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x ] bug report

* **Do you want to request a *feature* or report a *bug*?**
I want to report an error

* **What is the current behavior?**
App thrown errors

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  - Step 1: clone the repo
  - Step 2: npm install
  - Step 3: npm start
  - Step 4: navigate to Barrel or Detail
The app erred, this is the console log:

<img width="761" alt="screen shot 2017-12-04 at 1 35 14 pm" src="https://user-images.githubusercontent.com/775364/33539248-00540f00-d8f8-11e7-9d21-54a6bcf3fdc0.png">

Full log here: http://paste.ubuntu.com/26110596/

* **What is the expected behavior?**
App should works without error.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 5.0.1
- Browser: [Chrome 62]
- OS: MacOS 10.11.6

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by ericmartinezr** [comment]
This is a bug in RxJS https://github.com/ReactiveX/rxjs/issues/3151

**Comment by Bjeaurn** [comment]
Basically revert to 5.5.2 it's a temporary fix.

**Comment by Ks89** [comment]
Thank u @ericmartinezr , you saved my life 👍

**Comment by Bjeaurn** [comment]
Fixed in RxJS 5.5.4, you can try upgrading again. Worked safely in my complex application.

**Comment by envil** [comment]
The new update eliminated the problem. Thank you guys!
