### ISSUE TITLE
Lazy loading modules, should this work?

### ISSUE THREAD

**Issue by WillooWisp** [gdi2290/angular-starter#1933]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Currently my lazy loaded modules does not work, I guess since ng-router-loader is not included and used anymore. Any reason for this decision? Should I add it back or is there any other solution?

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
Latest version from master of this repo.

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by WillooWisp** [comment]
Does anyone know if lazy loading module is supported with latest code from master? Have you successfully lazy loaded any modules, i.e. loadChildren on route?

**Comment by Bjeaurn** [comment]
I'm running into issues getting lazy loading to work after upgrading most of the code (to reflect this repo). 

I'm stuck at `Error: Cannot find module '../demo/demo.module'.` in the browser, but got compilation to succeed so far.

I've switched to `@ngtools/webpack` instead of sticking with `ngc-webpack`, trying to get better results but have failed so far.

I'll probably create a separate issue with more background information and include some relevant configurations.

**Comment by Bjeaurn** [comment]
In the current, most up to date, version of the `angular-starter` at `master`, Lazyloading works fine.

**Comment by WillooWisp** [comment]
It does as long as you change to use the () => moduleToLazyLoad syntax instead of the string path syntax in loadChildren.

**Comment by WillooWisp** [comment]
Closing this, since it does indeed work with latest version.
