### ISSUE TITLE
Angular 4 starter

### ISSUE THREAD

**Issue by shaikhspear16** [gdi2290/angular-starter#1938]
For one of our projects we publish our own components used internally. We did it for Angular 2. We did not do for Angular 4. We will do for Angular 5 after 4 is done.

Where do I get angular 4 starter pack?

**Comment by simonmcl** [comment]
I asked the same thing 2 weeks ago here: https://github.com/gdi2290/angular-starter/issues/1929. There doesn't seem to have been a tagged release for angular 4, despite the project now being on Angular 5.

I think this is the last commit before a move to Angular 5. I took a copy of that and am using this as a base for my Angular 4 work now: https://github.com/gdi2290/angular-starter/commit/59af5242d1ed84980a4c9ca527f398104b63d076

**Comment by shaikhspear16** [comment]
@simonmcl I was able to create an Angular 4 starter with angular-cli by installing an older version of it.

`npm install -g @angular/cli@1.4`

Hope this helps someone.
