### ISSUE TITLE
Angular 5 and production build fails unless I set buildOptimizer in build-utils.js to false!

### ISSUE THREAD

**Issue by JoelParke** [gdi2290/angular-starter#1940]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
BUG -- I have a large project built around angular-starter where I must set (buildOptimizer=false) in config/build-utils.js in order that the 'projection' build can be loaded in the browser properly.  I show more details about this on stackoverflow.   See https://stackoverflow.com/questions/47706019/with-angular-5-and-webpack-for-production-build-i-see-please-add-a-ngmodule for more details.
NOTE: doing this increases the code size from 3.59 MB to 4.04 MB.  But it is not clear to me why this causes the load to fail -- perhaps the loader is confused???.  

* **What is the current behavior?**
Will not load in the browser even though there are not warnings or errors.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
The latest packages on 12/13/2017 -- 
- Angular version: 5.1
- Browser: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
- when I set buildOptimizer=false in the build-utils.js file -- all loads properly.  But I don't know enough of the internals to know what this is doing that breaks the loading... A clue is that the minimized code is 4.04 MB where it will load fine BUT when buildOptimizer=true, the minimized code is 3.59 MB, and will not load and it fails when attempting to load the first imported module - which in my case is the 'FormsModule', and when I set mangle:false, I see:
     
     Uncaught Error: Unexpected value 'FormsModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

**Comment by MADzO** [comment]
Check this #1921

**Comment by JoelParke** [comment]
THANKS!

**Comment by lanovoy** [comment]
Build optimizer only works for AoT builds. Have to be disabled for non-AoT.
