### ISSUE TITLE
Import dependencies

### ISSUE THREAD

**Issue by ojuniorbezerra** [gdi2290/angular-starter#1945]
Hi, 
I added some dependencies to my project, but the feature is not appearing.
Ex: MetisMenu.js, -> it is inside my node_modules but when I use the elements it appears as if it did not.
With jquery-slimscroll it was the same thing.
to try to escape this problem, I copied inside a folder lib o .js and in my module I am doing:
require("../lib/metisMenu.js");

but I have many dependencies, where and how would it be right?

**Comment by Bjeaurn** [comment]
I think you need to include a bit more about your configuration. Show us a piece of the code where you try to `import` the `node_modules` files you are referring to. 

Include any errors you may be receiving related to your issue, and feel free to use some formatting to make it easily readable for anyone passing by. This makes it easier to help you, and in turn, helps others figure out similar issues.

Suggest this issue gets closed until it is updated with more background information.
