### ISSUE TITLE
prod server doesn't work with current codebase

### ISSUE THREAD

**Issue by shahnj** [gdi2290/angular-starter#1946]
I am getting below error when trying to run the current version of https://github.com/gdi2290/angular-starter

These are the steps to reproduce below error:

#1 git clone --depth 1 https://github.com/AngularClass/angular-starter.git
#2 cd angular-starter
#3 npm install -g node-pre-gyp
#4 npm install
#5 npm run build:prod
#6 npm run server:prod

#7 browse to localhost:8080 on Google Chrome
#8 inspect shows below error: 

Uncaught Error: Unexpected value 't' imported by the module 't'. Please add a @NgModule annotation.
    at c (compiler.js:485)
    at compiler.js:15204
    at Array.forEach (<anonymous>)
    at t.getNgModuleMetadata (compiler.js:15187)
    at t._loadModules (compiler.js:34226)
    at t._compileModuleAndComponents (compiler.js:34187)
    at t.compileModuleAsync (compiler.js:34081)
    at t.compileModuleAsync (platform-browser-dynamic.js:230)
    at t.bootstrapModule (core.js:5568)
    at He (main.browser.ts:18)
    

NEED Help please, thank you very much.

**Comment by mrdavidwoodard** [comment]
Do you have angular-cli installed on your machine?

**Comment by shahnj** [comment]
Yes - 

user@iMac ~/work/angular-starter  (master)
$ ng -v
Unable to find "@angular/cli" in devDependencies.

Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest"

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
**@angular/cli: 1.0.0**
node: 6.11.0
os: darwin x64
@angular/animations: 5.1.1
@angular/common: 5.1.1
@angular/compiler: 5.1.1
@angular/core: 5.1.1
@angular/forms: 5.1.1
@angular/platform-browser: 5.1.1
@angular/platform-browser-dynamic: 5.1.1
@angular/platform-server: 5.1.1
@angular/router: 5.1.1
@angular/compiler-cli: 5.0.5
@ngtools/webpack: 1.9.1

**Comment by shahnj** [comment]
Yes - @angular/cli: 1.0.0

![image](https://user-images.githubusercontent.com/13139075/34136839-af27dd70-e435-11e7-83ee-9ba571906239.png)

**Comment by shahnj** [comment]
duplicate of https://github.com/gdi2290/angular-starter/issues/1921

closing - apologies for not following the template and raising without checking.
