### ISSUE TITLE
Segmentation Fault - Docker build

### ISSUE THREAD

**Issue by DanielNetzer** [gdi2290/angular-starter#1956]
* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

Submitting a bug when building a docker image using the current Dockerfile

* **What is the current behavior?**
when following the guidelines to add an external .scss and importing them to styles.scss, then importing styles.scss to the app.module.ts, trying to build a docker image fail with the following error

> 69% building modules 506/507 modules 1 active ...er.js!/tmp/app/src/styles/styles.scssSegmentation fault
> 
> npm ERR! Linux 4.4.108-boot2docker
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "webpack" "--" "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! cupo.io@1.0.1 webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"`
> npm ERR! Exit status 139
> npm ERR!
> npm ERR! Failed at the cupo.io@1.0.1 webpack script 'node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the cupo.io package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs cupo.io
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls cupo.io
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /tmp/app/npm-debug.log
> 
> npm ERR! Linux 4.4.108-boot2docker
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:aot:prod"
> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! cupo.io@1.0.1 build:aot:prod: `npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the cupo.io@1.0.1 build:aot:prod script 'npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the cupo.io package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs cupo.io
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls cupo.io
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /tmp/app/npm-debug.log
> 
> npm ERR! Linux 4.4.108-boot2docker
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:aot"
> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! cupo.io@1.0.1 build:aot: `npm run build:aot:prod`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the cupo.io@1.0.1 build:aot script 'npm run build:aot:prod'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the cupo.io package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm run build:aot:prod
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs cupo.io
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls cupo.io
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /tmp/app/npm-debug.log
> The command '/bin/sh -c cd /tmp/app &&    npm run build:aot &&    mv ./dist/* /usr/share/nginx/html/' returned a non-zero code: 1

to reproduce just use this project, import external .scss files using the guidelines and build a docker img,
OS is windows 10, i'm using Docker Quickstart Terminal.

* **What is the expected behavior?**

successful compilation

* **Please tell us about your environment:**

package.json file

> {
>   "name": "cupo.io",
>   "version": "1.0.1",
>   "description": "Cupo.io kit featuring Angular (Router, Http, Forms, Services, Tests, E2E, Coverage), Karma, Protractor, Jasmine, Istanbul, TypeScript, and Webpack by AngularClass",
>   "homepage": "https://cupo.io",
>   "license": "UNLICENSED",
>   "scripts": {
>     "build:aot:prod": "npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail",
>     "build:aot": "npm run build:aot:prod",
>     "build:aot:dev": "cross-env BUILD_AOT=1 npm run build:dev",
>     "build:dev": "npm run clean:dist && npm run webpack -- --config config/webpack.dev.js --progress --profile",
>     "build:docker": "npm run build:prod && docker build -t angular2-webpack-start:latest .",
>     "build:prod": "npm run clean:dist && npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail",
>     "build": "npm run build:dev",
>     "ci:aot": "cross-env BUILD_E2E=1 npm run lint && npm run test && npm run build:aot && npm run e2e",
>     "ci:jit": "cross-env BUILD_E2E=1 npm run lint && npm run test && npm run build:prod && npm run e2e",
>     "ci:nobuild": "npm run lint && npm test && npm run e2e",
>     "ci:testall": "cross-env BUILD_E2E=1 npm run lint && npm run test && npm run build:prod && npm run e2e && npm run build:aot && npm run e2e",
>     "ci:travis": "cross-env BUILD_E2E=1 npm run lint && npm run test && npm run build:aot && npm run e2e:travis",
>     "ci": "npm run ci:testall",
>     "clean:dll": "npm run rimraf -- dll",
>     "clean:aot": "npm run rimraf -- compiled",
>     "clean:dist": "npm run rimraf -- dist",
>     "clean:install": "npm set progress=false && npm install",
>     "clean": "npm cache clean --force && npm run rimraf -- node_modules doc coverage dist compiled dll",
>     "docker": "docker",
>     "docs": "npm run typedoc -- --options typedoc.json --exclude '**/*.spec.ts' ./src/",
>     "docs:compodoc": "compodoc -p tsconfig.json",
>     "docs:compodoc:serve": "compodoc -p tsconfig.json -s",
>     "docs:compodoc:serve:watch": "compodoc -p tsconfig.json -s -w",
>     "e2e:live": "npm-run-all -p -r server:prod:ci protractor:live",
>     "e2e:travis": "npm-run-all -p -r server:prod:ci protractor:delay",
>     "e2e": "npm-run-all -p -r server:prod:ci protractor",
>     "github-deploy:dev": "npm run webpack -- --config config/webpack.github-deploy.js --progress --profile --env.githubDev",
>     "github-deploy:prod": "npm run webpack -- --config config/webpack.github-deploy.js --progress --profile --env.githubProd",
>     "github-deploy": "npm run github-deploy:dev",
>     "lint": "npm run tslint \"src/**/*.ts\"",
>     "node": "node",
>     "postinstall": "npm run webdriver:update",
>     "postversion": "git push && git push --tags",
>     "preclean:install": "npm run clean",
>     "preversion": "npm test",
>     "protractor": "protractor",
>     "protractor:delay": "sleep 3 && npm run protractor",
>     "protractor:live": "protractor --elementExplorer",
>     "rimraf": "rimraf",
>     "server:dev:hmr": "npm run server:dev -- --hotOnly",
>     "server:aot:dev": "cross-env BUILD_AOT=1 npm run server:dev",
>     "server:dev": "npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/",
>     "server:prod": "http-server dist -c-1 --cors",
>     "server:prod:ci": "http-server dist -p 3000 -c-1 --cors",
>     "server": "npm run server:dev",
>     "start:hmr": "npm run server:dev:hmr",
>     "start": "npm run server:dev",
>     "start:aot": "npm run server:aot:dev",
>     "test": "npm run lint && karma start",
>     "tslint": "tslint",
>     "typedoc": "typedoc",
>     "version": "npm run build",
>     "watch:dev:hmr": "npm run watch:dev -- --hot",
>     "watch:dev": "npm run build:dev -- --watch",
>     "watch:aot:dev": "npm run build:aot:dev -- --watch",
>     "watch:prod": "npm run build:prod -- --watch",
>     "watch:aot:prod": "npm run build:aot:prod -- --watch",
>     "watch:test": "npm run test -- --auto-watch --no-single-run",
>     "watch": "npm run watch:dev",
>     "webdriver-manager": "node ./node_modules/protractor/bin/webdriver-manager",
>     "webdriver:start": "node ./node_modules/protractor/bin/webdriver-manager start",
>     "webdriver:update": "node ./node_modules/protractor/bin/webdriver-manager update",
>     "webpack-dev-server": "node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js",
>     "webpack": "node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js"
>   },
>   "dependencies": {
>     "@angular/animations": "~5.2.0",
>     "@angular/common": "~5.2.0",
>     "@angular/compiler": "~5.2.0",
>     "@angular/core": "~5.2.0",
>     "@angular/forms": "~5.2.0",
>     "@angular/platform-browser": "~5.2.0",
>     "@angular/platform-browser-dynamic": "~5.2.0",
>     "@angular/platform-server": "~5.2.0",
>     "@angular/router": "~5.2.0",
>     "@angular/http": "~5.2.0",
>     "core-js": "^2.5.1",
>     "http-server": "^0.10.0",
>     "ie-shim": "^0.1.0",
>     "reflect-metadata": "^0.1.10",
>     "rxjs": "^5.5.2",
>     "zone.js": "~0.8.18",
>     "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.9",
>     "@ngrx/effects": "4.1.1",
>     "@ngrx/entity": "4.1.1",
>     "@ngrx/router-store": "4.1.1",
>     "@ngrx/store": "4.1.1",
>     "@ngrx/store-devtools": "4.1.1",
>     "chart.js": "^2.5.0",
>     "easy-pie-chart": "^2.1.7",
>     "font-awesome": "^4.7.0",
>     "hammerjs": "^2.0.8",
>     "ng-mdb-pro": "git+https://oauth2:****************@git.mdbootstrap.com/mdb/angular/ng-pro.git#0ef0caed",
>     "ngrx-store-freeze": "^0.2.0",
>     "ngrx-store-localstorage": "^0.3.0",
>     "screenfull": "^3.3.2"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-optimizer": "^0.0.32",
>     "@angular/compiler-cli": "~5.2.0",
>     "@compodoc/compodoc": "^1.0.0-beta.15",
>     "@ngtools/webpack": "^1.9.3",
>     "@types/hammerjs": "^2.0.34",
>     "@types/jasmine": "2.5.45",
>     "@types/node": "^7.0.39",
>     "@types/uglify-js": "^2.6.28",
>     "@types/webpack": "^2.2.16",
>     "add-asset-html-webpack-plugin": "^1.0.2",
>     "angular2-template-loader": "^0.6.2",
>     "assets-webpack-plugin": "^3.5.1",
>     "awesome-typescript-loader": "^3.4.1",
>     "codelyzer": "~4.0.2",
>     "copy-webpack-plugin": "^4.0.1",
>     "cross-env": "^5.0.0",
>     "css-loader": "^0.28.0",
>     "exports-loader": "^0.6.4",
>     "expose-loader": "^0.7.3",
>     "extract-text-webpack-plugin": "~3.0.0",
>     "file-loader": "^0.11.1",
>     "find-root": "^1.0.0",
>     "gh-pages": "^1.0.0",
>     "html-webpack-plugin": "^2.28.0",
>     "imports-loader": "^0.7.1",
>     "inline-manifest-webpack-plugin": "^3.0.1",
>     "istanbul-instrumenter-loader": "2.0.0",
>     "jasmine-core": "^2.5.2",
>     "karma": "^1.6.0",
>     "karma-chrome-launcher": "^2.0.0",
>     "karma-coverage": "^1.1.1",
>     "karma-jasmine": "^1.1.0",
>     "karma-mocha-reporter": "^2.2.3",
>     "karma-remap-coverage": "^0.1.4",
>     "karma-sourcemap-loader": "^0.3.7",
>     "karma-webpack": "^2.0.4",
>     "ngc-webpack": "^4.0.2",
>     "node-sass": "^4.7.2",
>     "npm-run-all": "^4.0.2",
>     "optimize-js-plugin": "0.0.4",
>     "parse5": "^3.0.2",
>     "preload-webpack-plugin": "^1.2.2",
>     "protractor": "^5.1.1",
>     "raw-loader": "0.5.1",
>     "rimraf": "~2.6.1",
>     "sass-loader": "^6.0.3",
>     "script-ext-html-webpack-plugin": "^1.8.5",
>     "source-map-loader": "^0.2.1",
>     "string-replace-loader": "~1.3.0",
>     "style-loader": "^0.18.1",
>     "to-string-loader": "^1.1.5",
>     "ts-node": "^3.3.0",
>     "tslib": "^1.7.1",
>     "tslint": "~5.9.1",
>     "tslint-loader": "^3.5.3",
>     "typedoc": "^0.7.1",
>     "typescript": "next",
>     "uglifyjs-webpack-plugin": "^1.0.1",
>     "url-loader": "^0.5.8",
>     "webpack": "^3.8.1",
>     "webpack-dev-middleware": "^1.10.1",
>     "webpack-dev-server": "~2.7.1",
>     "webpack-dll-bundles-plugin": "^1.0.0-beta.5",
>     "webpack-merge": "~4.1.0"
>   },
>   "repository": {
>     "type": "git",
>     "url": "https://DanielNetzer@bitbucket.org/cupoio/application.git"
>   },
>   "engines": {
>     "node": ">= 4.2.1",
>     "npm": ">= 3"
>   }
> }
> 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by lanovoy** [comment]
Dockerfile was updated to do multi-staged build instead. If there are any issues with multi-staged build please open a new issue. Closing this one.
