### ISSUE TITLE
error when trying to add bootstrap 

### ISSUE THREAD

**Issue by iwxfer** [gdi2290/angular-starter#1968]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
I get error when trying to add boostrap with the instructions in the readme
"File to import not found or unreadable: bootstrap/scss/bootstrap.scss"

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Just followed the steps in the readme file to integrate boostrap

* **What is the expected behavior?**
Integrate boostrap but I get error

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 5.1
- Browser: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Error is:

```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/styles/styles.scss
Module build failed:
@import 'bootstrap/scss/bootstrap.scss';
^
      File to import not found or unreadable: bootstrap/scss/bootstrap.scss.
Parent style sheet: stdin
      in D:\dev\belatrix\astarter\src\styles\styles.scss (line 4, column 1)
 @ ./src/styles/styles.scss 4:14-124
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

```

**Comment by lanovoy** [comment]
Try changing 
`@import 'bootstrap/scss/bootstrap.scss';`

to
`@import '~bootstrap/scss/bootstrap.scss';`
