### ISSUE TITLE
Server does not start (searches for node_modules in `src/`) on master branch

### ISSUE THREAD

**Issue by TiS** [gdi2290/angular-starter#1970]
* **I'm submitting a ...**
   [x] bug report

* **What is the current behavior?**

1. Perform steps to install starter (git clone, npm install, npm start). Git clone on **master** branch.
2. Server complains about `@angular/common` not found in `src/node_modules/@angular/common`

* **What is the expected behavior?**

Starter server starts. Webpack looks for `@angular/common` in `./node_modules` instead of `src/node_modules`

**Comment by craigmatthew412** [comment]
I am having the opposite problem with this branch.  Webpack is looking for @angular/common in src/node_modules instead of node_modules at the project root

**Comment by craigmatthew412** [comment]
Also related to issue 1971.  The master branch worked perfectly fine as-is a few weeks ago when I cloned it originally...the @ngtools/webpack module was updated from 1.10.0 to 1.10.1 which caused the breaking change. I have validated the existing tsconfig works fine with @ngtools/webpack @ 1.10.0

**Comment by lanovoy** [comment]
Working solution in the #1971
