### ISSUE TITLE
npm run server broken since angular 5

### ISSUE THREAD

**Issue by bjorkegeek** [gdi2290/angular-starter#1974]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
a *bug*

* **What is the current behavior?**
Starting with commit 1fb04c5a185efd5b3ae27ca1552b253c3f088bbc "npm run server" fails while compiling. It seems to be looking for node_modules under the src directory instead of project root.

* **What is the expected behavior?**
"npm run server" should produce a working app, like it does before commit 1fb04c5a185efd5b3ae27ca1552b253c3f088bbc

* **What is the motivation / use case for changing the behavior?**
So that a user following the docs gets a running app

* **Please tell us about your environment:**

- OS: Fedora 26
- node v8.9.4
- npm 5.6.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

There is a workaround, which is issuing the command
```sh
ln -s ../node_modules src/node_modules
```

**Comment by almothafar** [comment]
You need to see full migration for angular 5, as for example, in `tsconfig.json`  and `tsconfig.webpack.json` the value of `"baseUrl": ""` should be `"baseUrl": "./src"`

**Comment by bjorkegeek** [comment]
What do you mean by that? I just forked a fresh repo, did `npm install` and `npm run server` and it fails.

Do you have a working tree, and is you `node_modules` sitting under `./src` or `.`?

**Comment by almothafar** [comment]
No, it should be a sibling to `src`, but I thought you were upgrading your project, anyway on my side, there are no issues, everything is totally fine.

**Comment by almothafar** [comment]
Oh, I think I got what the problem with you, "maybe".

in the package.json file, change `"@ngtools/webpack": "^1.8.0"`, to `"@ngtools/webpack": "1.10.0"`, delete `node_modules` and install modules again or just re-run `yarn` after that, when you do fresh install these days, you will get version `"@ngtools/webpack": "1.10.1",` in yarn something like this:

```
"@ngtools/webpack@^1.8.0":
  version "1.10.1"
  resolved "https://registry.yarnpkg.com/@ngtools/webpack/-/webpack-1.10.1.tgz#0af9de19a9716ce0247b6aad83ba9c5702766a03"
  dependencies:
    chalk "~2.2.0"
    enhanced-resolve "^3.1.0"
    loader-utils "^1.0.2"
    magic-string "^0.22.3"
    semver "^5.3.0"
    source-map "^0.5.6"
    tree-kill "^1.0.0"
    webpack-sources "^1.1.0"

```

And actually version `1.10.1` got critical bug, so force it to use older version like `1.10.0` but inside package.json.

TO make sure everything is going correctly, remove yarn.lock if you have it.

**Comment by bjorkegeek** [comment]
This solves it!
I'll submit a pull request.

**Comment by steven87vt** [comment]
Good morning, I download a clone at 9:36AM EST today and changing to "@ngtools/webpack": "1.10.0" allowed the app to run successfully. I am getting the following during npm install though, just in case its not me:

```
npm WARN @angular/compiler-cli@5.0.5 requires a peer of typescript@>=2.4.2 <2.5 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@5.0.5 requires a peer of @angular/compiler@5.0.5 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@2.1.1 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@2.1.1 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.24.1 requires a peer of typescript@2.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by almothafar** [comment]
@bjorkegeek have you seen the solution suggested here #1971

**Comment by steven87vt** [comment]
Just in case anyone else runs into this, making the following changes based on your feedback removed the dependency warnings for me. I had followed the startup guide on global installations, deleted npm lock file and node_modules with a fresh install. I am seeing a few deprecated warnings:

```
npm WARN deprecated @types/source-map@0.5.7: This is a stub types definition for source-map (https://github.com/mozilla/source-map). source-map provides its own type definitions, so you don't need @types/source-map installed!
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
```

Dependencies
```
change all "@angular/* -> "~5.2.6",
add "ajv": "^6.0.0"
```

Dev Dependencies
```
removed "@types/source-map": "^0.5.0",
changed to "@angular/compiler-cli": "~5.2.6",
changed to "@ngtools/webpack": "1.10.0",
changed to "codelyzer": "~4.1.0",
changed to "tslint": "~5.0.0",
changed to "typescript": "~2.6.2"
```

Now I have no missing dependencies warnings but I am still seeing deprecated warnings for

```
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
```

node -v: v9.6.1
npm -v: 5.6.0
rpm --query centos-release: centos-release-7-4.1708.el7.centos.x86_64

**Comment by SirZach** [comment]
I got burned on this. It'd be nice if there was some sort of CI/CD build pipeline that verified each commit to master

**Comment by bjorkegeek** [comment]
This is not an issue raised by a commit but rather an issue of an external package being upgraded causing breakage. To be safe, the project would have to switch to using exact versions of all packages.
