### ISSUE TITLE
How i change the order of css

### ISSUE THREAD

**Issue by hjnp** [gdi2290/angular-starter#1982]
Hey folks, i just have a question, i have on /styles.scss import an css for bootstrap
and my problem is, in each component "page" i have like one div wrapping all content like: 

<div class="page-x">Content of page</div>

on this componentent css file i want modify styles of bootstrap loaded in original /styles/styles.css
but not changes, only work, if i put next to import of bootstrap in this styles.css file. 

How can i change the order of this css?

like on final bumdle.css 
1ª bootstrap 
2ª all css's from all componentes in the angular app

**Comment by lanovoy** [comment]
I believe this should already be the case, but you can also try removing import of styles.scss from the app.component.ts and instead adding it into webpack.common.js as an entry point: 

`  const entry = {
    polyfills: './src/polyfills.browser.ts',
    main:      './src/main.browser.ts',
    styles: './src/styles.scss'
1};`
