### ISSUE TITLE
npm install complains cannot find module tsickle

### ISSUE THREAD

**Issue by kingvagabond** [gdi2290/angular-starter#1990]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ *] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

npm start fails

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Follow the steps specified in the README.md, and the output of npm start shows errors.

* **What is the expected behavior?**

npm start should start server locally

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

Windows 10, git-bash terminal, npm 5.6.0, node: 8.10.0. Chrome 

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kingvagabond** [comment]
Use npm run npm start will meet error as:

Error: Cannot find module 'tsickle'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

I tried use yarn after npm install, and somehow it's fine. tsickle is not specified in package.json, but yarn can find it and settle it down.

**Comment by almothafar** [comment]
Duplicates of #1589 and #1974
