### ISSUE TITLE
No Upgrage to NG6  ?

### ISSUE THREAD

**Issue by gaojinbo010** [gdi2290/angular-starter#2012]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @TipeIO](https://twitter.com/TipeIO)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 4.x.x
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by govi2010** [comment]
@gaojinbo010  Please check branch migrate-to-webpack4 . which is angular 6 added

**Comment by WillooWisp** [comment]
Can you please share any release schedule, feels like this repo has come to a stall when it comes to keeping up with dependent package versions.

**Comment by govi2010** [comment]
@WillooWisp  I don't know when will master branch be updated. but We have branch with latest version packages. 
Branch Name: migrate-to-webpack4

**Comment by govi2010** [comment]
@aledpardo  I think easy would be to close our angular 6 branch and put you code inside source folder.
Then just install needed package from your project to new cloned project. 

I think that will be easy if you have not customize our webpack files.......

**Comment by aledpardo** [comment]
@govi2010 thanks for quick reply.

I'll try this approach, but I'm sure my webpack files were customized a bit.

**Comment by lanovoy** [comment]
Are there any known issues with feature/migrate-to-webpack4 branch? If not, we can create a pull request into master.

**Comment by lanovoy** [comment]
After 2 weeks of testing in our project, didn't find any significant issues, so the branch was merged into master.
For reference this is the PR https://github.com/gdi2290/angular-starter/pull/2019
