### ISSUE TITLE
Failed on production server.

### ISSUE THREAD

**Issue by nimatullah** [gdi2290/angular-starter#2023]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @TipeIO](https://twitter.com/TipeIO)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

It should build successfully.

* **What is the current behavior?**

> `**ERROR in src/main.browser.ts(42,41): error TS2339: Property 'decorateModuleRef' does not exist on type '{ production: boolean; }'.**
`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation/use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 6.0.7
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by nimatullah** [comment]
anyone

**Comment by nimatullah** [comment]
Found my issue.

**Comment by oskrgg** [comment]
Hi, I'm having the same Error, can you show how you fixed it? Thanks

**Comment by oskrgg** [comment]
I found it. The thing is that Im trying to migrate from previous boilerplate to current boilerplate. And was trying to run `npm run build:prod` and this ERROR occurs:
 `**ERROR in src/main.browser.ts(55,41): error TS2339: Property 'decorateModuleRef' does not exist on type '{ production: boolean; }'.**` 

Notice that forgot to upgrade my `environment.prod.ts` where `decorateModuleRef` is declarated.
